# 命令执行 docker compose -f docker-compose-environment.yml up -d
services:
  mysql:
    image: mysql
    container_name: mysql-j
    restart: always
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "13306:3306"
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    networks:
      - network_jay

  # phpmyadmin https://hub.docker.com/_/phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-j
    hostname: phpmyadmin
    ports:
      - "8899:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network_jay

  # Redis
  redis:
    image: redis
    container_name: redis-j
    restart: always
    hostname: redis
    privileged: true
    ports:
      - "16379:6379"
    volumes:
      - ./redis/data:/redis/data
      - ./redis/logs:/redis/logs
      - ./redis/redis.conf:/redis/redis.conf
    command: redis-server /redis/redis.conf
    networks:
      - network_jay
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # RedisAdmin https://github.com/joeferner/redis-commander
  redis-admin:
    image: spryker/redis-commander:0.8.0
    container_name: redis-admin-j
    hostname: redis-commander
    restart: always
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
      - LANG=C.UTF-8
      - LANGUAGE=C.UTF-8
      - LC_ALL=C.UTF-8
    networks:
      - network_jay
    depends_on:
      redis:
        condition: service_healthy

  # rabbitmq
  # 账户密码admin/admin
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq-j
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    command: rabbitmq-server
    volumes:
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins

networks:
  network_jay:
    driver: bridge